services:
  mysql:
    image: mysql:latest
    container_name: mysql_url_shortener
    environment:
      MYSQL_ROOT_PASSWORD: "admin"
      MYSQL_DATABASE: "urlShortener"
      MYSQL_USER: "urlShortener"
      MYSQL_PASSWORD: "urlShortener"
      TZ: "Asia/Tokyo"
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    ports:
      - "3306:3306"
